application: alwaysprototyping
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /lightbox
  static_dir: lightbox

- url: /corridor
  static_dir: corridor

- url: /expression
  static_dir: expression

- url: /arraies
  static_dir: arraies

- url: /programing/static
  static_dir: programing/static

- url: /programing.*
  script: programing/programing.py

- url: /name/static
  static_dir: name/static

- url: /name.*
  script: name/name.py

- url: /lifelog/static
  static_dir: lifelog/static

- url: /math/static
  static_dir: math/static


- url: /landingpage/static
  static_dir: landingpage/static

- url: /static
  static_dir: static

- url: .*
  script: main.py
